stages:
  - deploy
delpoy:
  stage: deploy
  only:
    - master
  script:
    - cd /wwwroot/yyt
    - git remote -v
    - ssh -T git@192.168.108.210 << EOF
    - > yes
    - > EOF
    - git pull
    - echo "first deploy"